### ISSUE TITLE
bayes optimizaton + pytorch

### ISSUE THREAD

**Issue by yzbx** [ISCAS007/torchseg#21]
# tensor * numpy
```
# tensor * numpy (okay)
# numpy * tensor (failed)
loss = loss + l2_reg * l2_loss + l1_reg * l1_loss (failed)
loss = loss + l2_loss * l2_reg + l1_loss * l1_reg
```

**Comment by yzbx** [comment]
# a abnormal bug for pytorch + bayes optimization
```
Traceback (most recent call last):                                                      File "test/pspnet_test.py", line 288, in <module>
    hyperopt.tpe()
  File "/home/yzbx/git/torchseg/utils/model_hyperopt.py", line 97, in bayes
    bo.maximize(init_points=1,n_iter=1,kappa=2)
  File "/home/yzbx/bin/miniconda3/envs/new/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 259, in maximize
    **self._acqkw)
  File "/home/yzbx/bin/miniconda3/envs/new/lib/python3.6/site-packages/bayes_opt/helpers.py", line 63, in acq_max
    if max_acq is None or -res.fun[0] >= max_acq:
IndexError: too many indices for array

```

**Comment by yzbx** [comment]
# skopt
val\_miou* use part of dataset
val\_miou use full of dataset

| base\_lr | l1\_reg | l2\_reg | val\_miou* | val\_miou |
| - | - | - | - | - |
| 1.53e-3  | 2.38e-4 | 2.70e-4 | 0.234 | ? |
| 0.01 | 5.57e-7 | 9.29e-4 | 0.231 | ? |

**Comment by yzbx** [comment]
# hyperopt002
search [base_lr, l1_reg, l2_reg]
```
python test/pspnet_test.py --test=hyperopt --upsample_type=bilinear \
--n_epoch=200 --optimizer=sgd --use_reg=True --note=hyperopt002 \
--batch_size=4 --backbone_name=vgg16 --hyperopt=skopt \
--midnet_scale=15 --dataset_use_part=True --backbone_pretrained=True
```
## result
`minimize score=0.7602                                                          
minimize param [0.01, 1e-07, 1e-07]
`
## note
remove l1_reg, fix base_lr, replace sgd with adam, change backbone to resnet50 ?
## target
find the best l2_reg for pytorch

**Comment by yzbx** [comment]
# hyperopt003
```
python test/pspnet_test.py --batch_size=4 --use_reg=True --backbone_pretrained=True \
--midnet_scale=15 --upsample_type=bilinear --dataset_use_part=True --test=hyperopt \
--note=hyperopt004 --hyperopt=loop
```
## result
todo
## note
todo
## target
find the best normalization ways for image

**Comment by yzbx** [comment]
# hyperopt004
```
python test/pspnet_test.py --batch_size=4 --use_reg=True \
--backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=True \
--test=hyperopt --note=hyperopt004 --hyperopt=loop
```
## result
![screenshot from 2018-09-23 14-53-44](https://user-images.githubusercontent.com/5005182/45925054-8bdb0900-bf40-11e8-8bca-1b39083d8fb3.png)

## note
caffe are more stable, var is small
cityscapes have the best result, mean and max is best.
## target
find the best normalization method for cityscapes dataset

**Comment by yzbx** [comment]
### hyperopt006
```
python test/pspnet_test.py --batch_size=4 --use_reg=True \
--backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=320 \
--norm_ways=caffe --hyperkey=config.model.l2_reg \
--test=hyperopt --note=hyperopt006 --hyperopt=loop 
```

**Comment by yzbx** [comment]
# hyperopt007
```
python test/pspnet_test.py --batch_size=4 --use_reg=True \
--backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=320 \
--hyperkey=dataset.norm_ways --test=hyperopt \
--note=hyperopt007 --hyperopt=loop
```
## target
set dataset size from 32 to 320

**Comment by yzbx** [comment]
# hyperopt008
```
python test/pspnet_test.py --batch_size=4 --use_reg=True \
--backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=32 \
--hyperkey=dataset.norm_ways --test=hyperopt \
--note=hyperopt008 --hyperopt=loop \
--augmentation=False
```
## target
set dataset size to 32 and remove augmentation, target to solve overfit

**Comment by yzbx** [comment]
# hyperopt011 use_lr_mult + backbone_pretrained
```
python test/pspnet_test.py --batch_size=4 --use_reg=True \
--backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=32 \
--hyperkey=dataset.norm_ways,backbone_pretrained --test=hyperopt \
--note=hyperopt011 --hyperopt=loop
```

**Comment by yzbx** [comment]
# hyperopt014
| note,learning_rate  | mean train/iou |  mean val/iou |   n_epoch |
|:-------------------------|------------:|----------:|----------:|
| ('hyperopt014', 0.0001)  |    0.782894 |  0.370021 |       100 |
| ('hyperopt014', 0.0002)  |    0.799771 |  0.371424 |       100 |
| ('hyperopt014', 0.0005)  |    0.756845 |  0.363612 |       100 |
| ('hyperopt014', 0.001)   |    0.684718 |  0.342896 |       100 |
| ('hyperopt014', '1e-05') |    0.731833 |  0.323429 |       100 |
| ('hyperopt014', '2e-05') |    0.747784 |  0.334623 |       100 |
| ('hyperopt014', '5e-05') |    0.758231 |  0.359602 |       100 |

**Comment by yzbx** [comment]
# 015

# 016
```
python test/pspnet_test.py --dataset_use_part=320 --backbone_pretrained=True --net_name=psp_edge \
 --midnet_scale=15 --upsample_type=bilinear --hyperkey=model.edge_base_weight --batch_size=4 \
--note=wo_bn_016
```

**Comment by yzbx** [comment]
# 019 fcn 8, 16 and 32
| note | upsample_layer | midnet_scale |
| fcn8_019 | 5 | 3 |
| fcn16_019| 4 | 5 |
| fcn32_019 | 3 | 10 |

```
python test/pspnet_test.py --net_name=fcn --upsample_layer=5 --backbone_name=vgg16 --backbone_pretrained=True --note=fcn32_019 --midnet_scale=3 --batch_size=4 --dataset_use_part=320 --hyperkey=dataset.norm_ways --test=hyperopt --hyperopt=loop --hyperopt_calls=25
```

**Comment by yzbx** [comment]
# use_lr_mult021
```
python test/pspnet_test.py --batch_size=4 --backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=320 --hyperkey=model.use_lr_mult --test=hyperopt \
--note=use_lr_mult021 --hyperopt=loop --hyperopt_calls=6
```

**Comment by yzbx** [comment]
# lr_mult022
```
python test/pspnet_test.py --batch_size=4 --backbone_pretrained=True --midnet_scale=15 \
--upsample_type=bilinear --dataset_use_part=320  --use_lr_mult=True \
--upsample_layer=5 --use_momentum=True \
--hyperkey=model.changed_lr_mult,model.new_lr_mult \
--test=hyperopt --note=use_lr_mult021 --hyperopt=loop --hyperopt_calls=24
```

**Comment by yzbx** [comment]
# midnet_scale024
### voc input size test
```
python test/pspnet_test.py --backbone_pretrained=True --backbone_name=vgg19 \
--upsample_type=bilinear --midnet_scale=8 --batch_size=4 --note=midnet_scale024 \
--test=hyperopt --hyperkey=model.midnet_scale --hyperopt_calls=4 \
--use_momentum=False --upsample_layer=3
```

# midnet_scale025
### voc input size test
```
python test/pspnet_test.py --backbone_pretrained=True --backbone_name=vgg19 \
--upsample_type=bilinear --midnet_scale=8 --batch_size=4 --note=midnet_scale025 \
--test=hyperopt --hyperkey=model.midnet_scale --hyperopt_calls=4 \
--use_momentum=True --upsample_layer=5
```
